2019-02-06T10:58:39|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\Admin\eclipse-workspace\Laser_DAQ_Camera\Laser_DAQ_Camera_App.py", line 29, in <module>
    app = Laser_DAQ_Camera_App(sys.argv)
  File "C:\LabPrograms\Python\BaseMicroscopeModified_ScopeFoundry\BaseMicroscopeAppModified.py", line 16, in __init__
    super().__init__(*kwds) # *kwds is needed since in the main we pass as argument sys.argv. Without
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\base_app.py", line 332, in __init__
    self.setup()
  File "C:\Users\Admin\eclipse-workspace\Laser_DAQ_Camera\Laser_DAQ_Camera_App.py", line 10, in setup
    from CameraHardware import HamamatsuHardware
  File "C:\LabPrograms\Python\Camera-ScopeFoundry\CameraHardware.py", line 8, in <module>
    import CameraDevice
  File "C:\LabPrograms\Python\Camera-ScopeFoundry\CameraDevice.py", line 1499, in <module>
    raise DCAMException("DCAM initialization failed with error code " + str(error_code))
CameraDevice.DCAMException: DCAM initialization failed with error code -2147483130

