2019-02-06T12:26:15|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\Admin\eclipse-workspace\Laser_DAQ_Camera\Laser_DAQ_Camera_App.py", line 38, in <module>
    app = Laser_DAQ_Camera_App(sys.argv)
  File "C:\LabPrograms\Python\BaseMicroscopeModified_ScopeFoundry\BaseMicroscopeAppModified.py", line 16, in __init__
    super().__init__(*kwds) # *kwds is needed since in the main we pass as argument sys.argv. Without
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\base_app.py", line 332, in __init__
    self.setup()
  File "C:\Users\Admin\eclipse-workspace\Laser_DAQ_Camera\Laser_DAQ_Camera_App.py", line 26, in setup
    self.add_measurement(DaqControlledMeasurement(self))
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\measurement.py", line 93, in __init__
    self.setup()
  File "C:\Users\Admin\eclipse-workspace\Laser_DAQ_Camera\DaqControlledMeasurement.py", line 27, in setup
    self.ui = load_qt_ui_file(self.ui_filename)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\helper_funcs.py", line 64, in load_qt_ui_file
    ui = uic.loadUi(ui_filename)
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyQt5\uic\__init__.py", line 226, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyQt5\uic\Loader\loader.py", line 72, in loadUi
    return self.parse(filename, resource_suffix, basedir)
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyQt5\uic\uiparser.py", line 1013, in parse
    document = parse(filename)
  File "C:\ProgramData\Anaconda3\lib\xml\etree\ElementTree.py", line 1197, in parse
    tree.parse(source, parser)
  File "C:\ProgramData\Anaconda3\lib\xml\etree\ElementTree.py", line 587, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Admin\\eclipse-workspace\\Laser_DAQ_Camera\\form.ui'

