2020-07-27T12:37:01|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\measurement.py", line 25, in run
    self.measurement._thread_run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\measurement.py", line 179, in _thread_run
    self.run()
  File "C:\LabPrograms\Python\DAQ_Laser_Camera\PROCHIP_Measurement_cell_detection.py", line 148, in run
    self.start_triggered_Acquisition(self.settings['acq_freq'])
  File "C:\LabPrograms\Python\DAQ_Laser_Camera\PROCHIP_Measurement_cell_detection.py", line 423, in start_triggered_Acquisition
    self.start_digital_rising_edge(self.ni_do_1)
  File "C:\LabPrograms\Python\DAQ_Laser_Camera\PROCHIP_Measurement_cell_detection.py", line 357, in start_digital_rising_edge
    digitalHW.write_value()
  File "C:\LabPrograms\Python\nidaqmx_test\ni_do_hardware.py", line 44, in write_value
    self.DO_device.write(self.value.val)
AttributeError: 'NI_DO_hw' object has no attribute 'DO_device'

