2021-07-13T12:02:47|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\Users\Admin\anaconda3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\LabPrograms\Python\OBIS_ScopeFoundry\laser_hardware.py", line 35, in connect
    self.laser = LaserDevice(port=self.port.val, debug=self.debug_mode.val)
  File "C:\LabPrograms\Python\OBIS_ScopeFoundry\laser_device.py", line 14, in __init__
    self.ser = ser = serial.Serial(port=self.port, baudrate=921600,
  File "C:\Users\Admin\anaconda3\envs\scopefoundry\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\Admin\anaconda3\envs\scopefoundry\lib\site-packages\serial\serialutil.py", line 240, in __init__
    self.open()
  File "C:\Users\Admin\anaconda3\envs\scopefoundry\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM7': FileNotFoundError(2, 'Impossibile trovare il file specificato.', None, 2)

2021-07-13T12:51:57|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\LabPrograms\Python\HexSimAnalyser\HexSimAnalyser_measurement.py", line 434, in loadFile
    self.load_h5_file()
  File "C:\LabPrograms\Python\HexSimAnalyser\HexSimAnalyser_measurement.py", line 238, in load_h5_file
    available_datasets = self.open_PROCHIP_h5_file()
  File "C:\LabPrograms\Python\HexSimAnalyser\HexSimAnalyser_measurement.py", line 280, in open_PROCHIP_h5_file
    available_datasets = self.set_dataset(idx = 0)
  File "C:\LabPrograms\Python\HexSimAnalyser\HexSimAnalyser_measurement.py", line 315, in set_dataset
    self.imageRaw = stack
  File "C:\LabPrograms\Python\HexSimAnalyser\HexSimAnalyser_measurement.py", line 186, in imageRaw
    xcorr = self.calculate_carrier(img_raw[:,frame_index,:,:]) # calculates the power spectrum of imageRaw for the first phase
  File "C:\LabPrograms\Python\HexSimAnalyser\HexSimAnalyser_measurement.py", line 475, in calculate_carrier
    sum_prepared_comp[k, :, :] = sum_prepared_comp[k, :, :] + img[l, :, :] * M[k, l]
ValueError: operands could not be broadcast together with shapes (512,512) (512,700) 

2021-07-13T12:52:09|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\LabPrograms\Python\HexSimAnalyser\HexSimAnalyser_measurement.py", line 434, in loadFile
    self.load_h5_file()
  File "C:\LabPrograms\Python\HexSimAnalyser\HexSimAnalyser_measurement.py", line 238, in load_h5_file
    available_datasets = self.open_PROCHIP_h5_file()
  File "C:\LabPrograms\Python\HexSimAnalyser\HexSimAnalyser_measurement.py", line 280, in open_PROCHIP_h5_file
    available_datasets = self.set_dataset(idx = 0)
  File "C:\LabPrograms\Python\HexSimAnalyser\HexSimAnalyser_measurement.py", line 315, in set_dataset
    self.imageRaw = stack
  File "C:\LabPrograms\Python\HexSimAnalyser\HexSimAnalyser_measurement.py", line 186, in imageRaw
    xcorr = self.calculate_carrier(img_raw[:,frame_index,:,:]) # calculates the power spectrum of imageRaw for the first phase
  File "C:\LabPrograms\Python\HexSimAnalyser\HexSimAnalyser_measurement.py", line 475, in calculate_carrier
    sum_prepared_comp[k, :, :] = sum_prepared_comp[k, :, :] + img[l, :, :] * M[k, l]
ValueError: operands could not be broadcast together with shapes (512,512) (512,700) 

2021-07-13T12:52:41|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\LabPrograms\Python\HexSimAnalyser\HexSimAnalyser_measurement.py", line 434, in loadFile
    self.load_h5_file()
  File "C:\LabPrograms\Python\HexSimAnalyser\HexSimAnalyser_measurement.py", line 238, in load_h5_file
    available_datasets = self.open_PROCHIP_h5_file()
  File "C:\LabPrograms\Python\HexSimAnalyser\HexSimAnalyser_measurement.py", line 280, in open_PROCHIP_h5_file
    available_datasets = self.set_dataset(idx = 0)
  File "C:\LabPrograms\Python\HexSimAnalyser\HexSimAnalyser_measurement.py", line 315, in set_dataset
    self.imageRaw = stack
  File "C:\LabPrograms\Python\HexSimAnalyser\HexSimAnalyser_measurement.py", line 186, in imageRaw
    xcorr = self.calculate_carrier(img_raw[:,frame_index,:,:]) # calculates the power spectrum of imageRaw for the first phase
  File "C:\LabPrograms\Python\HexSimAnalyser\HexSimAnalyser_measurement.py", line 475, in calculate_carrier
    sum_prepared_comp[k, :, :] = sum_prepared_comp[k, :, :] + img[l, :, :] * M[k, l]
ValueError: operands could not be broadcast together with shapes (512,512) (512,700) 

2021-07-13T12:56:07|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\LabPrograms\Python\HexSimAnalyser\HexSimAnalyser_measurement.py", line 434, in loadFile
    self.load_h5_file()
  File "C:\LabPrograms\Python\HexSimAnalyser\HexSimAnalyser_measurement.py", line 238, in load_h5_file
    available_datasets = self.open_PROCHIP_h5_file()
  File "C:\LabPrograms\Python\HexSimAnalyser\HexSimAnalyser_measurement.py", line 280, in open_PROCHIP_h5_file
    available_datasets = self.set_dataset(idx = 0)
  File "C:\LabPrograms\Python\HexSimAnalyser\HexSimAnalyser_measurement.py", line 315, in set_dataset
    self.imageRaw = stack
  File "C:\LabPrograms\Python\HexSimAnalyser\HexSimAnalyser_measurement.py", line 186, in imageRaw
    xcorr = self.calculate_carrier(img_raw[:,frame_index,:,:]) # calculates the power spectrum of imageRaw for the first phase
  File "C:\LabPrograms\Python\HexSimAnalyser\HexSimAnalyser_measurement.py", line 475, in calculate_carrier
    sum_prepared_comp[k, :, :] = sum_prepared_comp[k, :, :] + img[l, :, :] * M[k, l]
ValueError: operands could not be broadcast together with shapes (512,512) (512,700) 

2021-07-13T13:00:09|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\LabPrograms\Python\HexSimAnalyser\HexSimAnalyser_measurement.py", line 434, in loadFile
    self.load_h5_file()
  File "C:\LabPrograms\Python\HexSimAnalyser\HexSimAnalyser_measurement.py", line 238, in load_h5_file
    available_datasets = self.open_PROCHIP_h5_file()
  File "C:\LabPrograms\Python\HexSimAnalyser\HexSimAnalyser_measurement.py", line 280, in open_PROCHIP_h5_file
    available_datasets = self.set_dataset(idx = 0)
  File "C:\LabPrograms\Python\HexSimAnalyser\HexSimAnalyser_measurement.py", line 315, in set_dataset
    self.imageRaw = stack
  File "C:\LabPrograms\Python\HexSimAnalyser\HexSimAnalyser_measurement.py", line 186, in imageRaw
    xcorr = self.calculate_carrier(img_raw[:,frame_index,:,:]) # calculates the power spectrum of imageRaw for the first phase
  File "C:\LabPrograms\Python\HexSimAnalyser\HexSimAnalyser_measurement.py", line 475, in calculate_carrier
    sum_prepared_comp[k, :, :] = sum_prepared_comp[k, :, :] + img[l, :, :] * M[k, l]
ValueError: operands could not be broadcast together with shapes (512,512) (512,700) 

2021-07-13T14:21:53|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\LabPrograms\Python\HexSimAnalyser\HexSimAnalyser_measurement.py", line 434, in loadFile
    self.load_h5_file()
  File "C:\LabPrograms\Python\HexSimAnalyser\HexSimAnalyser_measurement.py", line 238, in load_h5_file
    available_datasets = self.open_PROCHIP_h5_file()
  File "C:\LabPrograms\Python\HexSimAnalyser\HexSimAnalyser_measurement.py", line 280, in open_PROCHIP_h5_file
    available_datasets = self.set_dataset(idx = 0)
  File "C:\LabPrograms\Python\HexSimAnalyser\HexSimAnalyser_measurement.py", line 315, in set_dataset
    self.imageRaw = stack
  File "C:\LabPrograms\Python\HexSimAnalyser\HexSimAnalyser_measurement.py", line 186, in imageRaw
    xcorr = self.calculate_carrier(img_raw[:,frame_index,:,:]) # calculates the power spectrum of imageRaw for the first phase
  File "C:\LabPrograms\Python\HexSimAnalyser\HexSimAnalyser_measurement.py", line 475, in calculate_carrier
    sum_prepared_comp[k, :, :] = sum_prepared_comp[k, :, :] + img[l, :, :] * M[k, l]
ValueError: operands could not be broadcast together with shapes (512,512) (512,700) 

2021-07-13T15:04:29|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\envs\scopefoundry\lib\site-packages\ScopeFoundry\measurement.py", line 244, in start_stop
    self._start()
  File "C:\Users\Admin\anaconda3\envs\scopefoundry\lib\site-packages\ScopeFoundry\measurement.py", line 134, in _start
    raise RuntimeError("Cannot start a new measurement while still measuring")
RuntimeError: Cannot start a new measurement while still measuring

2021-07-13T15:40:55|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\Users\Admin\anaconda3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\LabPrograms\Python\OBIS_ScopeFoundry\laser_hardware.py", line 35, in connect
    self.laser = LaserDevice(port=self.port.val, debug=self.debug_mode.val)
  File "C:\LabPrograms\Python\OBIS_ScopeFoundry\laser_device.py", line 14, in __init__
    self.ser = ser = serial.Serial(port=self.port, baudrate=921600,
  File "C:\Users\Admin\anaconda3\envs\scopefoundry\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\Admin\anaconda3\envs\scopefoundry\lib\site-packages\serial\serialutil.py", line 240, in __init__
    self.open()
  File "C:\Users\Admin\anaconda3\envs\scopefoundry\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM6': PermissionError(13, 'Accesso negato.', None, 5)

